import type { RawUpdate } from "@/lib/intelligence/types";

export const rawUpdates: RawUpdate[] = [
  {
    id: "chatgpt-2026-04-08-memory-controls",
    product: "ChatGPT",
    title: "ChatGPT launches team memory controls for account-level context",
    body: "Team admins can now define which memory sources agents may reuse across shared workspaces, making long-running project context more predictable for analysts and product leads.",
    publishedAt: "2026-04-08",
    source: "OpenAI release notes",
  },
  {
    id: "chatgpt-2026-04-04-operator-handoffs",
    product: "ChatGPT",
    title: "ChatGPT rolls out operator task handoffs for project workflows",
    body: "Teams can assign an operator to gather context, draft next steps, and pass the workflow back to a human reviewer inside shared projects.",
    publishedAt: "2026-04-04",
    source: "OpenAI product blog",
  },
  {
    id: "chatgpt-2026-03-28-deep-research-exports",
    product: "ChatGPT",
    title: "ChatGPT adds deep research exports inside project spaces",
    body: "Research sessions can now export cited findings into reusable project briefs, linking search output to downstream planning and review workflows.",
    publishedAt: "2026-03-28",
    source: "OpenAI product blog",
  },
  {
    id: "chatgpt-2026-03-20-templates",
    product: "ChatGPT",
    title: "ChatGPT opens workflow templates for sales and strategy teams",
    body: "Reusable templates turn prompts, memory settings, and shared review steps into repeatable workflows for go-to-market and product planning teams.",
    publishedAt: "2026-03-20",
    source: "OpenAI release notes",
  },
  {
    id: "chatgpt-2026-03-12-credits",
    product: "ChatGPT",
    title: "ChatGPT introduces flexible credits for advanced agent runs",
    body: "The new pricing model separates everyday usage from premium agent tasks, giving teams more control over how autonomous work is budgeted.",
    publishedAt: "2026-03-12",
    source: "OpenAI pricing update",
  },
  {
    id: "chatgpt-2026-03-04-coding-workspace",
    product: "ChatGPT",
    title: "ChatGPT expands coding workspace with repo context panes",
    body: "Developers can pin repository context, terminal notes, and active plans alongside model output, turning coding sessions into structured workflows.",
    publishedAt: "2026-03-04",
    source: "OpenAI developer update",
  },
  {
    id: "claude-2026-04-07-research-trails",
    product: "Claude",
    title: "Claude expands research workflows with source trails",
    body: "Each research answer now preserves source trails and follow-up prompts so analysts can revisit search logic across multi-step briefs.",
    publishedAt: "2026-04-07",
    source: "Anthropic changelog",
  },
  {
    id: "claude-2026-04-02-agent-checklists",
    product: "Claude",
    title: "Claude adds long-running agent checklists for team reviews",
    body: "Agent tasks can pause at required checkpoints, letting research or product teams review steps before execution continues.",
    publishedAt: "2026-04-02",
    source: "Anthropic product blog",
  },
  {
    id: "claude-2026-03-26-memory-presets",
    product: "Claude",
    title: "Claude introduces memory presets for recurring brief formats",
    body: "Teams can store persistent instructions and context blocks for recurring market scans, planning memos, and executive updates.",
    publishedAt: "2026-03-26",
    source: "Anthropic changelog",
  },
  {
    id: "claude-2026-03-18-code-summaries",
    product: "Claude",
    title: "Claude opens code session summaries inside project workspaces",
    body: "Claude Code now writes reusable summaries after each terminal session, helping teams carry memory and rationale between engineering reviews.",
    publishedAt: "2026-03-18",
    source: "Anthropic developer update",
  },
  {
    id: "claude-2026-03-11-review-lanes",
    product: "Claude",
    title: "Claude adds shared review lanes for PM and strategy teams",
    body: "Workspaces can now route drafts into shared lanes where collaborators leave comments, approve next steps, and keep a visible workflow trail.",
    publishedAt: "2026-03-11",
    source: "Anthropic workspace update",
  },
  {
    id: "claude-2026-03-01-seat-bundles",
    product: "Claude",
    title: "Claude updates pricing with analyst seat bundles",
    body: "New team bundles package higher research limits, manager controls, and shared collaboration lanes under one pricing tier.",
    publishedAt: "2026-03-01",
    source: "Anthropic pricing update",
  },
  {
    id: "perplexity-2026-04-08-collections",
    product: "Perplexity",
    title: "Perplexity launches collections for recurring market scans",
    body: "Collections group search threads, saved sources, and weekly outputs into repeatable intelligence workflows for research teams.",
    publishedAt: "2026-04-08",
    source: "Perplexity product blog",
  },
  {
    id: "perplexity-2026-04-03-session-memory",
    product: "Perplexity",
    title: "Perplexity adds memory for follow-up research sessions",
    body: "Users can carry previous research preferences, saved companies, and recurring questions across ongoing search sessions.",
    publishedAt: "2026-04-03",
    source: "Perplexity changelog",
  },
  {
    id: "perplexity-2026-03-27-analyst-mode",
    product: "Perplexity",
    title: "Perplexity introduces analyst mode with multi-source compare",
    body: "Analyst mode automatically searches across multiple sources, compares claims, and assembles a draft brief with follow-on prompts.",
    publishedAt: "2026-03-27",
    source: "Perplexity product blog",
  },
  {
    id: "perplexity-2026-03-19-brief-sharing",
    product: "Perplexity",
    title: "Perplexity expands team brief sharing for research groups",
    body: "Research leads can now publish answer threads as shared brief pages with comment-ready collaboration views.",
    publishedAt: "2026-03-19",
    source: "Perplexity changelog",
  },
  {
    id: "perplexity-2026-03-10-research-credits",
    product: "Perplexity",
    title: "Perplexity rolls out enterprise research credits pricing",
    body: "The updated pricing plan introduces flexible credits for higher-volume search, analyst workflows, and admin reporting.",
    publishedAt: "2026-03-10",
    source: "Perplexity pricing update",
  },
  {
    id: "perplexity-2026-03-02-api-snippets",
    product: "Perplexity",
    title: "Perplexity opens API snippets for research workflow builders",
    body: "New developer snippets help teams inject search results into internal dashboards, recurring reports, and custom workflow automations.",
    publishedAt: "2026-03-02",
    source: "Perplexity developer update",
  },
  {
    id: "notion-ai-2026-04-06-project-brief-generator",
    product: "Notion AI",
    title: "Notion AI ships a project brief generator inside docs",
    body: "Teams can turn scattered notes into structured briefs with timelines, risks, and workflow next steps directly inside shared documents.",
    publishedAt: "2026-04-06",
    source: "Notion release notes",
  },
  {
    id: "notion-ai-2026-04-01-standup-memory",
    product: "Notion AI",
    title: "Notion AI adds workspace memory for recurring standups",
    body: "Persistent meeting context helps teams reuse project status, blockers, and follow-up decisions without rewriting the same prompts each week.",
    publishedAt: "2026-04-01",
    source: "Notion AI update",
  },
  {
    id: "notion-ai-2026-03-25-connected-search",
    product: "Notion AI",
    title: "Notion AI launches connected search across project hubs",
    body: "Search now spans docs, tasks, and team databases so workspaces can answer cross-project questions with clearer workflow context.",
    publishedAt: "2026-03-25",
    source: "Notion product blog",
  },
  {
    id: "notion-ai-2026-03-17-board-automation",
    product: "Notion AI",
    title: "Notion AI rolls out meeting follow-up board automations",
    body: "Workspace automations assign owners, draft summaries, and create next-step tasks after notes are captured in shared meeting pages.",
    publishedAt: "2026-03-17",
    source: "Notion AI update",
  },
  {
    id: "notion-ai-2026-03-09-knowledge-connectors",
    product: "Notion AI",
    title: "Notion AI introduces team knowledge connectors beta",
    body: "Connected knowledge sources give teams a wider search surface and stronger collaboration context for recurring planning work.",
    publishedAt: "2026-03-09",
    source: "Notion product blog",
  },
  {
    id: "notion-ai-2026-02-28-multiseat-pricing",
    product: "Notion AI",
    title: "Notion AI updates pricing for multi-seat workspace plans",
    body: "The new packaging lowers entry cost for multi-seat adoption while keeping premium AI workflow features for higher tiers.",
    publishedAt: "2026-02-28",
    source: "Notion pricing update",
  },
  {
    id: "cursor-2026-04-07-background-agents",
    product: "Cursor",
    title: "Cursor adds background agents for repo maintenance",
    body: "Developers can run autonomous repository tasks in the background, with checkpoints for code review, planning, and approval.",
    publishedAt: "2026-04-07",
    source: "Cursor changelog",
  },
  {
    id: "cursor-2026-04-02-memory-snapshots",
    product: "Cursor",
    title: "Cursor expands codebase memory snapshots between sessions",
    body: "Project memory now keeps architecture notes, prior prompts, and recent files so coding workflows continue across sessions.",
    publishedAt: "2026-04-02",
    source: "Cursor changelog",
  },
  {
    id: "cursor-2026-03-24-review-boards",
    product: "Cursor",
    title: "Cursor launches workflow boards for code review tasks",
    body: "Review boards turn coding tasks, feedback, and follow-up fixes into a visible team workflow inside the IDE.",
    publishedAt: "2026-03-24",
    source: "Cursor product blog",
  },
  {
    id: "cursor-2026-03-16-symbol-search",
    product: "Cursor",
    title: "Cursor improves search across symbols and docs",
    body: "Cross-repo search can now pull symbol context, project docs, and generated notes into one developer-facing answer flow.",
    publishedAt: "2026-03-16",
    source: "Cursor changelog",
  },
  {
    id: "cursor-2026-03-08-governance-pricing",
    product: "Cursor",
    title: "Cursor introduces team seats and governance controls",
    body: "The updated pricing and admin model packages seat-based governance, usage visibility, and shared workspace controls for teams.",
    publishedAt: "2026-03-08",
    source: "Cursor pricing update",
  },
  {
    id: "cursor-2026-02-27-mcp-gallery",
    product: "Cursor",
    title: "Cursor opens an MCP connector gallery for dev workflows",
    body: "Developers can browse connectors for repos, docs, and issue trackers to stitch together richer coding workflows.",
    publishedAt: "2026-02-27",
    source: "Cursor developer update",
  },
  {
    id: "devin-2026-04-05-sprint-playbooks",
    product: "Devin",
    title: "Devin ships sprint planning agent playbooks",
    body: "Prebuilt playbooks let engineering leads hand sprint planning, ticket triage, and follow-on execution to configurable agents.",
    publishedAt: "2026-04-05",
    source: "Cognition release notes",
  },
  {
    id: "devin-2026-03-31-ticket-memory",
    product: "Devin",
    title: "Devin adds persistent task memory across tickets",
    body: "Agent runs can now retain project conventions, debugging history, and recurring context across related engineering tickets.",
    publishedAt: "2026-03-31",
    source: "Cognition product blog",
  },
  {
    id: "devin-2026-03-23-debug-search",
    product: "Devin",
    title: "Devin expands debugging search traces for engineering teams",
    body: "Search traces show which logs, repos, and docs the agent consulted before proposing a fix or next step.",
    publishedAt: "2026-03-23",
    source: "Cognition developer update",
  },
  {
    id: "devin-2026-03-15-reviewer-inbox",
    product: "Devin",
    title: "Devin launches a collaboration inbox for reviewer handoffs",
    body: "Agent output can now route into a reviewer inbox where humans inspect work, comment, and relaunch the workflow if needed.",
    publishedAt: "2026-03-15",
    source: "Cognition workspace update",
  },
  {
    id: "devin-2026-03-07-agent-pricing",
    product: "Devin",
    title: "Devin updates usage-based pricing for agent runs",
    body: "The new model breaks out premium execution tasks, memory retention, and team administration into clearer pricing buckets.",
    publishedAt: "2026-03-07",
    source: "Cognition pricing update",
  },
  {
    id: "devin-2026-02-26-timeline-replay",
    product: "Devin",
    title: "Devin adds IDE timeline replay for code investigations",
    body: "Engineering teams can replay the agent timeline, inspect tool calls, and recover workflow context after debugging sessions.",
    publishedAt: "2026-02-26",
    source: "Cognition developer update",
  },
  {
    id: "gemini-2026-04-08-workspace-panels",
    product: "Gemini",
    title: "Gemini opens workspace panels for docs and code",
    body: "Workspace panels let users pull documents, code, and search results into one planning surface for ongoing multi-step work.",
    publishedAt: "2026-04-08",
    source: "Google AI update",
  },
  {
    id: "gemini-2026-04-03-agent-mode",
    product: "Gemini",
    title: "Gemini adds an agent mode for cross-app actions",
    body: "Agent mode coordinates Gmail, Docs, and Calendar steps so users can trigger multi-app workflows from one prompt.",
    publishedAt: "2026-04-03",
    source: "Google AI product blog",
  },
  {
    id: "gemini-2026-03-29-project-memory",
    product: "Gemini",
    title: "Gemini improves memory across long-running project chats",
    body: "Project conversations now retain goals, prior decisions, and linked documents for stronger recall across extended planning cycles.",
    publishedAt: "2026-03-29",
    source: "Google AI update",
  },
  {
    id: "gemini-2026-03-21-shareable-canvases",
    product: "Gemini",
    title: "Gemini expands collaboration with shareable AI canvases",
    body: "Shareable canvases help teams co-edit prompts, structured outputs, and workflow plans inside a collaborative workspace.",
    publishedAt: "2026-03-21",
    source: "Google Workspace update",
  },
  {
    id: "gemini-2026-03-13-cli-preview",
    product: "Gemini",
    title: "Gemini launches a developer preview for CLI tools",
    body: "The new CLI connects coding prompts, repository context, and terminal workflows for developer-facing use cases.",
    publishedAt: "2026-03-13",
    source: "Google developer update",
  },
  {
    id: "gemini-2026-03-05-advanced-pricing",
    product: "Gemini",
    title: "Gemini refreshes premium plan pricing tiers",
    body: "Updated plan tiers package more agent actions, memory capacity, and workspace integrations for advanced users.",
    publishedAt: "2026-03-05",
    source: "Google AI pricing update",
  },
  {
    id: "figma-ai-2026-04-04-critique-agents",
    product: "Figma AI",
    title: "Figma AI launches design critique agents for teams",
    body: "Critique agents review layouts, identify issues, and route findings back into collaborative design workflows.",
    publishedAt: "2026-04-04",
    source: "Figma AI release notes",
  },
  {
    id: "figma-ai-2026-03-30-asset-search",
    product: "Figma AI",
    title: "Figma AI adds searchable asset intelligence across files",
    body: "Teams can search assets, comments, and prior explorations across files to speed up design workflows and reuse.",
    publishedAt: "2026-03-30",
    source: "Figma AI update",
  },
  {
    id: "figma-ai-2026-03-22-brand-memory",
    product: "Figma AI",
    title: "Figma AI ships memory for reusable brand guidance",
    body: "Brand guidance memory helps teams preserve reusable rules, asset context, and approval preferences across projects.",
    publishedAt: "2026-03-22",
    source: "Figma AI update",
  },
  {
    id: "figma-ai-2026-03-14-handoff-automation",
    product: "Figma AI",
    title: "Figma AI rolls out workflow automations for handoff docs",
    body: "The new workflow builder turns design notes into delivery docs, assigns follow-up steps, and keeps collaborators aligned.",
    publishedAt: "2026-03-14",
    source: "Figma product blog",
  },
  {
    id: "figma-ai-2026-03-06-agency-seats",
    product: "Figma AI",
    title: "Figma AI introduces collaboration seats for agencies",
    body: "The new pricing package gives agencies shared access to critique workflows, approval history, and premium AI review tools.",
    publishedAt: "2026-03-06",
    source: "Figma pricing update",
  },
  {
    id: "figma-ai-2026-02-27-dev-mode-prompts",
    product: "Figma AI",
    title: "Figma AI opens developer mode prompts for design-to-code",
    body: "Developer mode now includes AI prompts that bridge layouts, code snippets, and handoff workflows for engineering teams.",
    publishedAt: "2026-02-27",
    source: "Figma developer update",
  },
];
